apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgres
spec:
  storageClassName: rook-cephfs-retain-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi